EShop/Areas/Admin/Controllers/ShippingController.cs
using EShop.Models;
using EShop.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EShop.Areas.Admin.Controllers
{
	[Area("Admin")]
	[Route("Admin/Shipping")]
	[Authorize(Roles = "Admin,Staff")]
	public class ShippingController : Controller
	{
		private readonly DataContext _dataContext;
		public ShippingController(DataContext context)
		{
			_dataContext = context;
		}

		[Route("Index")]
		public async Task<IActionResult> Index()
		{
			var shippingList = await _dataContext.Shippings.ToListAsync();
			ViewBag.Shippings = shippingList;
			return View();
		}

		[HttpPost]
		[Route("StoreShipping")]
		public async Task<IActionResult> StoreShipping(ShippingModel shippingModel, string phuong, string quan, string tinh, decimal price)
		{
			shippingModel.City = tinh;
			shippingModel.District = quan;
			shippingModel.Ward = phuong;
			shippingModel.Price = price;

			try
			{
				var existingShipping = await _dataContext.Shippings
					.AnyAsync(x => x.City == tinh && x.District == quan && x.Ward == phuong);

				// Kiểm tra có dữ liệu chưa
				if (existingShipping)
				{
					return Ok(new { duplicate = true, message = "Dữ liệu trùng lặp." });
				}

				_dataContext.Shippings.Add(shippingModel);
				await _dataContext.SaveChangesAsync();

				return Ok(new { success = true, message = "Thêm shipping thành công." });
			}
			catch (Exception) {
				return StatusCode(500, "An error occurred while adding shipping.");
			}
		}

		public async Task<IActionResult> Delete(int Id)
		{
			ShippingModel shipping = await _dataContext.Shippings.FindAsync(Id);

			_dataContext.Shippings.Remove(shipping);
			await _dataContext.SaveChangesAsync();

			TempData["success"] = "Shipping đã được xoá thành công.";

			return  RedirectToAction("Index");
		}



	}
}

EShop/Areas/Admin/Views/Shipping/Index.cshtml
@model ShippingModel

@{
	ViewData["title"] = "Create Shipping";
}

<style type="text/css">
	.css_select_div {
		text-align: center;
	}

	.css_select {
		display: inline-table;
		width: 25%;
		padding: 5px;
		margin: 5px 2%;
		border: solid 1px #686868;
		border-radius: 5px;
	}
</style>

<h4>Create Shipping</h4>
<div class="col-md-9">

	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="form-group">
		<label>Chọn</label>
		<select class="css_select" id="tinh" name="tinh" title="Chọn Tỉnh Thành">
			<option value="0">Tỉnh Thành</option>
		</select>
	</div>
	<div class="form-group">
		<label>Chọn</label>
		<select class="css_select" id="quan" name="quan" title="Chọn Quận Huyện">
			<option value="0">Quận Huyện</option>
		</select>
	</div>
	<div class="form-group">
		<label>Chọn</label>
		<select class="css_select" id="phuong" name="phuong" title="Chọn Phường Xã">
			<option value="0">Phường Xã</option>
		</select>
	</div>

	<div class="form-group">
		<label>Nhập giá</label>
		<input asp-for="Price" id="price-shipping" class="form-control" />
	</div>

	<div class="form-group">
		<button type="button" class="btn btn-primary btn-add-shipping">Create</button>
	</div>

	<h2>Shipping List</h2>
	<table class="table table-striped" id="myTable">
		<thead>
			<tr>
				<th>City</th>
				<th>District</th>
				<th>Ward</th>
				<th>Price</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var shipping in ViewBag.Shippings)
			{
				<tr>
					<td>@shipping.City</td>
					<td>@shipping.District</td>
					<td>@shipping.Ward</td>
					<td>@shipping.Price.ToString("#,##0 VNĐ")</td>
					<td>
						<a onclick="return confirm('Bạn chắc chắn muốn xoá.')" href="@Url.Action("Delete","Shipping", new {id = shipping.Id})" class="btn btn-danger">Delete</a>
					</td>
				</tr>
			}
		</tbody>
	</table>


	<a asp-action="Index" asp-controller="Shipping">Back to List Shipping</a>
</div>

@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}

	<script>

		$(".btn-add-shipping").click(function () {
			var tinh = $("#tinh").find('option:selected').text();
			var quan = $("#quan").find('option:selected').text();
			var phuong = $("#phuong").find('option:selected').text();
			var price = $("#price-shipping").val();

			// Kiểm tra nếu có trường nào bị bỏ trống
			if (tinh == '' || quan == '' || phuong == '' || price == '') {
				Swal.fire("Vui lòng không bỏ trống.");
			}
			else {
				$.ajax({
					type: "POST",
					url: "@Url.Action("StoreShipping", "Shipping")",
					data: { tinh: tinh, quan: quan, phuong: phuong, price: price },

					success: function (result) {
						// Kiểm tra phản hồi từ server
						if (result.success) {
							Swal.fire("Thêm vận chuyển thành công. Load lại page để thấy data");
							// location.reload();
						}
						else if (result.duplicate) {
							Swal.fire("Dữ liệu trùng lặp.");
						}
					}
				});
			}
		})


		$(document).ready(function () {
			//Lấy tỉnh thành
			$.getJSON('https://esgoo.net/api-tinhthanh/1/0.htm', function (data_tinh) {
				if (data_tinh.error == 0) {
					$.each(data_tinh.data, function (key_tinh, val_tinh) {
						$("#tinh").append('<option value="' + val_tinh.id + '">' + val_tinh.full_name + '</option>');
					});
					$("#tinh").change(function (e) {
						var idtinh = $(this).val();
						//Lấy quận huyện
						$.getJSON('https://esgoo.net/api-tinhthanh/2/' + idtinh + '.htm', function (data_quan) {
							if (data_quan.error == 0) {
								$("#quan").html('<option value="0">Quận Huyện</option>');
								$("#phuong").html('<option value="0">Phường Xã</option>');
								$.each(data_quan.data, function (key_quan, val_quan) {
									$("#quan").append('<option value="' + val_quan.id + '">' + val_quan.full_name + '</option>');
								});
								//Lấy phường xã
								$("#quan").change(function (e) {
									var idquan = $(this).val();
									$.getJSON('https://esgoo.net/api-tinhthanh/3/' + idquan + '.htm', function (data_phuong) {
										if (data_phuong.error == 0) {
											$("#phuong").html('<option value="0">Phường Xã</option>');
											$.each(data_phuong.data, function (key_phuong, val_phuong) {
												$("#phuong").append('<option value="' + val_phuong.id + '">' + val_phuong.full_name + '</option>');
											});
										}
									});
								});

							}
						});
					});

				}
			});
		});
	</script>

}